version: '3.8'

services:
  laravel7.4:
    build:
      context: .
      dockerfile: docker/php7.4-apache/Dockerfile
    container_name: laravel7.4
    ports:
      - "8000:80"
    volumes:
      - ./src/php7.4:/var/www/html
    networks:
      - laravel-net

  laravel8.3:
    build:
      context: .
      dockerfile: docker/php8.3-apache/Dockerfile
    container_name: laravel8.3
    ports:
      - "8001:80"
    volumes:
      - ./src/php8.3:/var/www/html
    networks:
      - laravel-net

networks:
  laravel-net:
    external: true
    name: laravel-net
